### ISSUE TITLE
ID_STRUCTURE in EMPLOYEE può essere NULL?

### ISSUE THREAD

**Issue by lilpilgit** [lilpilgit/Aesthetic#21]
Se cancello una struttura, ID_STRUCTURE in EMPLOYEE lo impost a NULL ma bisogna poi gestire magari a livello applicativo in una sezione con tutti i dipendenti da RICOLLOCARE

**Comment by Andreab-git** [comment]
Si, fai in modo che possa essere null che poi lo riassegneremo nella pagina amministratore dedicata dove gestisce gli utenti
