### ISSUE TITLE
[MODIFICA GUARDA I COMMENTI IMPORTANTE!!!! ]AGGIUNGERE ID_PRODOTTO E ID_PRENOTAZIONE IN COUPON NELLO SCHEMA RELAZIONALE

### ISSUE THREAD

**Issue by lilpilgit** [lilpilgit/Aesthetic#33]
Una volta aggiunto, modifica il titolo e aggiungi SCRIVERE TRIGGER PER ID_PRODOTTO e ID_PRENOTAZIONE in COUPON (perchè non possono essere entrambi settati, uno dei due dovrà essere NULL alternativamente)
@Andreab-git

**Comment by lilpilgit** [comment]
Collegare coupon a prodotto come hai fatto È SBAGLIATO! perchè lo stai legando a un prodotto che è del catalogo ma devi legarlo a un ACQUISTO (PURCHASE nel DB) e sinceramente non so al momento come fare (forse relazione ternaria...da discutere). La soluzione più veloce è permettere di usare i coupon solo per le prenotazioni

**Comment by lilpilgit** [comment]
.

**Comment by Andreab-git** [comment]
Coupon ha solo la relazione riferita alle prenotazioni, Chiudo!
