### ISSUE TITLE
Attributi calcolati

### ISSUE THREAD

**Issue by Andreab-git** [lilpilgit/Aesthetic#5]
Vanno o non vanno nello schema relazionale???

**Comment by lilpilgit** [comment]
Usarli come attributi regolari e specificare poi come vengono calcolati

**Comment by Andreab-git** [comment]
AGGIORNARE MINIMONDO!

**Comment by lilpilgit** [comment]
AGGIUNTO TRIGGER CHE AUMENTA E DIMINUISCE IL NUMERO DI INSERIMENTI SULLA BASE DEI DIPENDENTI AGGIUNTI O RIMOSSI
