### ISSUE TITLE
Immagini nel database?

### ISSUE THREAD

**Issue by Andreab-git** [lilpilgit/Aesthetic#8]
Dato che ciascun prodotto avrà un'immagine, queste andranno gestite all'interno del database oppure vanno gestite a livello applicativo?

**Comment by lilpilgit** [comment]
_From Quora_
**If you make a gallery for your website, would you store images in a database or just a folder in the server or is there any other way to do it?**

Don’t store the images in database. Its almost never a good idea. (can be in some cases).

I can think of two options.

First one. You have a normal traffic website not something, lets say you have hundred of visits a day. Then you store the images on a folder, and you keep the url or image name in the database and use it to render. You need to keep in mind cases of a webfarm if you have more than one server, then the images needs to be kept on a shared physical location accessible by all servers.

Second option. You have lots of visitors, and you want to make sure your content is rendered quickly always. Then you store the images/videos and such similar content using a CDN(content delivery network) service. Just google it, and you will find many companies online that provide this service. This way is used by many of the high traffic websites, and I think some big companies do build their own.

**Comment by lilpilgit** [comment]
_From dev.to 30 March_

**Saving images in a database or in the project's folder?**

Depends on the scale(#of users) of your application and frequency of access(lots of upload) . For any medium to large scale website -talking thousands of request and uploads, it is best to use an external file storage service like AWS S3.

From a cost standpoint, storing huge load of User files on the database or project folder is bad practice and will tie up resources for other things like codes file, templates, data, etc ..
